version: '3'
services:
  docker-mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: api_database
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      timeout: 10s
      retries: 10
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql_data

  spring-api-aws:
    build: ../crowdsensing-api
    container_name: springboot-api-aws
    environment:
      - DB_URL=jdbc:mysql://docker-mysql:3306/api_database?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    ports:
      - "8080:8080"
    depends_on:
      docker-mysql:
        condition:  service_healthy

volumes:
  mysql_data:
    driver: local