name: Build, Push to ECR, and Run on EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPO_NAME }}:latest .

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.ECR_REPO_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      # Step to fetch public IPs based on EC2 tags
      - name: Fetch EC2 Public IPs based on Tags
        id: fetch_ips
        run: |
          EC2_INSTANCE_ID_1=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=springboot-api-1" --query "Reservations[].Instances[].InstanceId" --output text)
          EC2_INSTANCE_ID_2=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=springboot-api-2" --query "Reservations[].Instances[].InstanceId" --output text)
          EC2_INSTANCE_ID_3=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=springboot-api-3" --query "Reservations[].Instances[].InstanceId" --output text)

          # Start the instances if they are stopped
          aws ec2 start-instances --instance-ids $EC2_INSTANCE_ID_1 $EC2_INSTANCE_ID_2 $EC2_INSTANCE_ID_3 --region ${{ secrets.AWS_REGION }}
          aws ec2 wait instance-running --instance-ids $EC2_INSTANCE_ID_1 $EC2_INSTANCE_ID_2 $EC2_INSTANCE_ID_3 --region ${{ secrets.AWS_REGION }}

          # Fetch the public IPs
          EC2_PUBLIC_IP_1=$(aws ec2 describe-instances --instance-ids $EC2_INSTANCE_ID_1 --query "Reservations[].Instances[].PublicIpAddress" --output text)
          EC2_PUBLIC_IP_2=$(aws ec2 describe-instances --instance-ids $EC2_INSTANCE_ID_2 --query "Reservations[].Instances[].PublicIpAddress" --output text)
          EC2_PUBLIC_IP_3=$(aws ec2 describe-instances --instance-ids $EC2_INSTANCE_ID_3 --query "Reservations[].Instances[].PublicIpAddress" --output text)

          # Export them as GitHub Actions environment variables
          echo "EC2_PUBLIC_IP_1=$EC2_PUBLIC_IP_1" >> $GITHUB_ENV
          echo "EC2_PUBLIC_IP_2=$EC2_PUBLIC_IP_2" >> $GITHUB_ENV
          echo "EC2_PUBLIC_IP_3=$EC2_PUBLIC_IP_3" >> $GITHUB_ENV

      # SSH and deploy to the first EC2 instance
      - name: SSH into EC2 instance 1 and run commands
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_PUBLIC_IP_1 << 'EOF'
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
            docker stop springboot-api-container || true
            docker rm springboot-api-container || true
            docker run -d --rm --name springboot-api-container -p 8080:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
          EOF

      # SSH and deploy to the second EC2 instance
      - name: SSH into EC2 instance 2 and run commands
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_PUBLIC_IP_2 << 'EOF'
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
            docker stop springboot-api-container || true
            docker rm springboot-api-container || true
            docker run -d --rm --name springboot-api-container -p 8080:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
          EOF

      # SSH and deploy to the third EC2 instance
      - name: SSH into EC2 instance 3 and run commands
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_PUBLIC_IP_3 << 'EOF'
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
            docker stop springboot-api-container || true
            docker rm springboot-api-container || true
            docker run -d --rm --name springboot-api-container -p 8080:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
          EOF
